### PR TITLE
[mciccale] Assignment4

### PR DESCRIPTION
**Pull request by mciccale**

### CODE REVIEW

**Comment by anaigmo** [comment]
Nice work! Just one thing:
* in task 7.2, you are not listing the individuals of :Person, only of its subclass(es)

**Comment by mciccale** [comment]
Great! Thanks for the feedback.

Do we need to update the assignment and make another PR?

**Comment by anaigmo** [comment]
you can commit and update this PR, no need to open another one

**Comment by mciccale** [comment]
Great! Done.

**Pull request merged**
